import Providers from "./providers"
import "./globals.css"

export const metadata = {
  title: "Finanssoreal",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
